##
## Calculate combined risks in the four UK nations (as far as data are available):
## - flooding
## - domestic fires
## - asylum seeker displacement
## - loneliness
## - health deprivation
## - digital exclusion
##
library(tidyverse)
library(rgdal)
library(xlsx)
library(httr)
library(readxl)

# devtools::install_github("matthewgthomas/brclib")  # install BRC data science package if needed
library(brclib)

source("init.r")

quants = 5  # how many fisher splits / quantiles to use

risky_lads_file = file.path(data.dir.out, "Multiple risks in Local Authorities.xlsx")  # Excel file for saving lists of Local Authorities with multiple risks
risky_lads_wb = createWorkbook()

#################################################################################################################
## Create list of Local Authorities that have a BRC presence (or not)
##
# Local Authority Districts (December 2019) Boundaries UK BUC
# source: https://geoportal.statistics.gov.uk/datasets/local-authority-districts-december-2019-boundaries-uk-buc
lad_bounds = readOGR("https://opendata.arcgis.com/datasets/3a4fa2ce68f642e399b4de07643eeed3_0.geojson")

# load BRC presence
# these files were generated for the Community Presence Map: https://gitlab.com/communitypresencemap/community-map/-/blob/master/data_preparation/prep%20web%20app%20data.r
brc_services = readOGR(dsn = file.path(data.dir.in, "brc", "services.geojson"), verbose = F)
brc_shops    = readOGR(dsn = file.path(data.dir.in, "brc", "shops.geojson"), verbose = F)
brc_props    = readOGR(dsn = file.path(data.dir.in, "brc", "props.geojson"), verbose = F)

# set to same CRS
lad_bounds   = spTransform(lad_bounds, map_proj)
brc_services = spTransform(brc_services, map_proj)
brc_shops    = spTransform(brc_shops, map_proj)
brc_props    = spTransform(brc_props, map_proj)

# find which LADs have BRC services/shops/properties
lad_service = lad_bounds %over% brc_services
lad_shops = lad_bounds %over% brc_shops
lad_props = lad_bounds %over% brc_props

##
## mark which LADs have BRC services, shops, properties
##
lad_service = lad_service %>% 
  mutate(BRC_services = ifelse(is.na(FID), "No", "Yes")) %>% 
  select(BRC_services)

lad_shops = lad_shops %>% 
  mutate(BRC_shops = ifelse(is.na(Shop.code), "No", "Yes")) %>% 
  select(BRC_shops)

lad_props = lad_props %>% 
  mutate(BRC_props = ifelse(is.na(UPC), "No", "Yes")) %>% 
  select(BRC_props)

# merge into LADs list
lad_brc = bind_cols(
  lad_bounds@data %>% select(lad17cd = lad19cd),
  lad_service,
  lad_shops,
  lad_props
)

rm(lad_bounds, brc_services, brc_shops, brc_props, lad_service, lad_shops, lad_props)


#################################################################################################################
## Load common datasets
##
uk_lsoa_imd = read_csv("https://github.com/matthewgthomas/IMD/raw/master/data/UK%20IMD%20domains.csv",  # pre-processed IMD data from https://github.com/matthewgthomas/IMD
                       col_types = cols(
                         .default = col_double(),
                         LSOA = col_character(),
                         Name = col_character(),
                         RUC = col_character()
                       ))

uk_msoa_alone = read_csv(file.path(data.dir.processed, "UK - Household composition - People - MSOA.csv")) %>%  # from `prep living alone.r`
  rename(msoa11cd = `geography code`)

lad_codes = read_csv(file.path(data.dir.in, "LAD 2017 to LAD 2019 codes.csv"))


#################################################################################################################
## England
## - fires in LSOAs
## - floods in LSOAs
## - displacement in LADs
## - loneliness in LSOAs
## - health deprivation in LSOAs
## - digital exclusion in LADs
##

##
## load all England data
##
# Middle Layer Super Output Areas (December 2011) Names and Codes in England and Wales
# source: https://geoportal.statistics.gov.uk/datasets/middle-layer-super-output-areas-december-2011-names-and-codes-in-england-and-wales
eng_msoa = read_csv("https://opendata.arcgis.com/datasets/6b82649791b3481692d63d39a653143c_0.csv")

eng_msoa_fires = read_csv(file.path(data.dir.processed, "Fires - MSOA - England.csv"))        # from `prep fires.r`
eng_msoa_floods = read_csv(file.path(data.dir.processed, "MSOAs in flood risk zones.csv"))   # from `prep flood risks.r`

eng_msoa_loneliness = read_csv("https://github.com/matthewgthomas/loneliness/raw/master/England/msoa_loneliness.csv")  # generated by Python code in https://github.com/matthewgthomas/loneliness

eng_msoa_alone = uk_msoa_alone  # from data loaded in 'common datasets' section

eng_lsoa_imd = uk_lsoa_imd %>% select(LSOA, IMD_decile, Health_decile)  # from data loaded in 'common datasets' section

eng_lad_displacement = read_csv(file.path(data.dir.processed, "UK - LAD - displacement.csv"))         # from `prep displacement.r`
eng_lad_destitution = read_csv(file.path(data.dir.processed, "Destitution - Local Authorities - whole UK.csv")) # from `prep destitution.r`
eng_lad_hle = read_csv(file.path(data.dir.processed, "Healthy life expectancy - Local Authorities - whole UK.csv"))  # from `prep healthy life expectancy .r`
eng_lad_digital = read_csv(file.path(data.dir.processed, "digital exclusion.csv")) %>%        # from `prep digital exclusion.r`
  rename(lad17cd = la_codes)

# Output Area to LSOA to MSOA to Local Authority District (December 2017) Lookup with Area Classifications in Great Britain
# source: http://geoportal.statistics.gov.uk/datasets/fe6c55f0924b4734adf1cf7104a0173e_0
# eng_lookup = read_csv(file.path("../../../../Data/", "Lookups, names and codes/OA to LSOA to MSOA to LAD.csv")) %>% 
eng_lookup = read_csv("https://opendata.arcgis.com/datasets/fe6c55f0924b4734adf1cf7104a0173e_0.csv") %>% 
  select(starts_with("LSOA"), starts_with("MSOA"), starts_with("LAD")) %>% 
  distinct()

##
## keep England data only
##
eng_msoa             = eng_msoa %>% filter(startsWith(MSOA11CD, "E"))
eng_msoa_fires       = eng_msoa_fires %>% filter(startsWith(MSOA11CD, "E"))
eng_msoa_floods      = eng_msoa_floods %>% filter(startsWith(MSOA11CD, "E"))
eng_msoa_loneliness  = eng_msoa_loneliness %>% filter(startsWith(msoa11cd, "E"))
eng_msoa_alone       = eng_msoa_alone %>% filter(startsWith(msoa11cd, "E"))
eng_lsoa_imd         = eng_lsoa_imd %>% filter(startsWith(LSOA, "E"))
eng_lad_displacement = eng_lad_displacement %>% filter(startsWith(LAD19CD, "E"))
eng_lad_destitution  = eng_lad_destitution %>% filter(startsWith(lad17cd, "E"))
eng_lad_digital      = eng_lad_digital %>% filter(startsWith(lad17cd, "E"))
eng_lad_hle          = eng_lad_hle %>% filter(startsWith(lad17cd, "E"))

##
## data tweaking
##
# rename flooding variable
eng_msoa_floods = eng_msoa_floods %>% rename(n_people_flood = n)

# loneliness: keep only loneliness indices >= 0 (and cut out unnecessary columns)
eng_msoa_loneliness = eng_msoa_loneliness %>% 
  # filter(loneills_2018 >= 0) %>% 
  select(msoa11cd, loneills_2018, loneills_2018_class)

##
## calculate fisher splits/categories for each risk
##
# fires
eng_msoa_fires = eng_msoa_fires %>% add_risk_quantiles("dens_fires", output.col = "fires")

# floods
eng_msoa_floods = eng_msoa_floods %>% add_risk_quantiles("n_people_flood", output.col = "floods")

# displacement
eng_lad_displacement = eng_lad_displacement %>% add_risk_quantiles("Sec95", output.col = "displacement")

# loneliness
eng_msoa_loneliness = eng_msoa_loneliness %>% add_risk_quantiles("loneills_2018", "lonely")

# healthy life expectancy
eng_lad_hle = eng_lad_hle %>% add_risk_quantiles("HLE_birth", "hle_birth")

# digital exclusion
eng_lad_digital = eng_lad_digital %>% add_risk_quantiles("digital_total_mult", "digital")

# living alone
eng_msoa_alone = eng_msoa_alone %>% add_risk_quantiles("prop_alone", "alone")

# deprivation - link the LSOAs to MSOAs and mark MSOAs as most deprived if any of their LSOAs are most-deprived
eng_msoa_imd = eng_lsoa_imd %>% 
  left_join(eng_lookup %>% select(LSOA11CD, MSOA11CD), by = c("LSOA" = "LSOA11CD")) %>% 
  
  # mark MSOAs with the most-deprived LSOA in its bounds
  group_by(MSOA11CD) %>% 
  summarise(Worst_Health_decile = min(Health_decile),
            Worst_IMD_decile = min(IMD_decile)) %>%
  
  mutate(health_q = case_when(
    Worst_Health_decile %in% c(1, 2) ~ 1,   # most deprived
    Worst_Health_decile %in% c(3, 4) ~ 2,
    Worst_Health_decile %in% c(5, 6) ~ 3,
    Worst_Health_decile %in% c(7, 8) ~ 4,
    Worst_Health_decile %in% c(9, 10) ~ 5   # least deprived
  ),
  
  imd_q = case_when(
    Worst_IMD_decile %in% c(1, 2) ~ 1,   # most deprived
    Worst_IMD_decile %in% c(3, 4) ~ 2,
    Worst_IMD_decile %in% c(5, 6) ~ 3,
    Worst_IMD_decile %in% c(7, 8) ~ 4,
    Worst_IMD_decile %in% c(9, 10) ~ 5   # least deprived
  ))

# migrant destitution and all destitution - already in deciles, so just convert to quintiles by halving and rounding up
# 10 = highest destitution; 1 = lowest
eng_lad_destitution = eng_lad_destitution %>% 
  mutate(destitution_q = ceiling(destitution_all / 2),
         migrant_dest_q = ceiling(destitution_migrant / 2)) %>% 
  
  # reverse-score the quantiles so highest destitution == 1
  mutate(destitution_q = (quants + 1) - destitution_q,
         migrant_dest_q = (quants + 1) - migrant_dest_q)


##
## combined risk at MSOA level: for everything except displacement and digital exclusion (because they're at a wider geography)
##
# merge all LSOA data into a single dataframe
eng_msoa_risk = eng_msoa %>% 
  left_join(eng_msoa_fires, by = "MSOA11CD") %>% 
  left_join(eng_msoa_floods, by = "MSOA11CD") %>% 
  left_join(eng_msoa_loneliness, by = c("MSOA11CD" = "msoa11cd")) %>% 
  left_join(eng_msoa_imd, by = "MSOA11CD") %>% 
  left_join(eng_msoa_alone, by = c("MSOA11CD" = "msoa11cd"))

# replace NAs with zeroes for the risk quintiles
eng_msoa_risk = eng_msoa_risk %>% 
  replace_na(list(fires_q  = 99,
                  floods_q = 99, 
                  lonely_q = 99,
                  health_q = 99,
                  imd_q    = 99,
                  alone_q  = 99))

# calculate combined risks
eng_msoa_risk = eng_msoa_risk %>% 
  mutate(Risk1 = ifelse(fires_q == 1,  "Fires", NA),
         Risk2 = ifelse(floods_q == 1, "Flooding", NA),
         Risk3 = ifelse(lonely_q == 1, "Loneliness", NA),
         Risk4 = ifelse(health_q == 1, "Health deprivation", NA),
         Risk5 = ifelse(alone_q == 1,  "Living alone", NA),
         Risk6 = ifelse(imd_q == 1,    "IMD", NA)) %>% 
  mutate(CombinedRisk = paste(Risk1, Risk2, Risk3, Risk4, Risk5, Risk6, sep = ", ")) %>% 
  
  mutate(CombinedRisk = gsub("NA, ", "", CombinedRisk)) %>%  # get rid of NAs
  mutate(CombinedRisk = gsub(", NA", "", CombinedRisk)) %>%  # get rid of any trailing NA
  
  select(-starts_with("Risk"))

##
## combined risk at LAD level: for everthing
##
# take the MSOA risks and aggregate into LADs - by grouping them with the worst MSOA risk in each category
eng_lad_risk = eng_msoa_risk %>% 
  # lookup the LADs for these MSOAs
  left_join(eng_lookup %>% select(MSOA11CD, LAD17CD), by = "MSOA11CD") %>% 
  
  # take the score of the worst-performing MSOA within each LAD
  group_by(LAD17CD) %>% 
  summarise(worst_fires_q  = min(fires_q),
            worst_floods_q = min(floods_q),
            worst_lonely_q = min(lonely_q),
            worst_health_q = min(health_q),
            worst_alone_q  = min(alone_q),
            worst_imd_q    = min(imd_q),
            
            # calculate highest/worst risks in each LAD
            worst_fires  = ifelse(all(is.na(dens_fires)), NA, max(dens_fires, na.rm = T)),  # only calculate max. if not all MSOAs contain NA
            worst_floods = ifelse(all(is.na(n_people_flood)), NA, max(n_people_flood, na.rm = T)),  # only calculate max. if not all MSOAs contain NA
            worst_lonely = max(loneills_2018, na.rm = T),
            worst_health = min(Worst_Health_decile, na.rm = T),
            worst_alone  = (sum(n_one_person_hh, na.rm = T) + sum(n_lone_parents, na.rm = T)) / sum(n_people_total, na.rm = T),  # proportion of people living alone in whole LAD
            worst_imd    = min(Worst_IMD_decile, na.rm = T),
            
            # calculate averages (medians) for each risk in each LAD
            median_fires  = median(dens_fires, na.rm = T),
            median_floods = median(n_people_flood, na.rm = T),
            median_lonely = median(loneills_2018, na.rm = T),
            median_health = median(Worst_Health_decile, na.rm = T),
            median_alone  = median(prop_alone, na.rm = T),
            median_imd    = median(Worst_IMD_decile, na.rm = T)) %>% 
  
  left_join(lad_codes, by = "LAD17CD") %>%   # get LAD 2019 codes
  
  # merge displacement and digital exclusion
  left_join(eng_lad_displacement, by = "LAD19CD") %>%
  left_join(eng_lad_digital, by = c("LAD17CD" = "lad17cd")) %>% 
  left_join(eng_lad_hle, by = c("LAD17CD" = "lad17cd")) %>% 
  left_join(eng_lad_destitution, by = c("LAD17CD" = "lad17cd"))

# calculate combined risks
eng_lad_risk = eng_lad_risk %>% 
  mutate(Risk1  = ifelse(worst_fires_q == 1,  "Fires", NA),
         Risk2  = ifelse(worst_floods_q == 1, "Flooding", NA),
         Risk3  = ifelse(displacement_q == 1, "Displacement", NA),
         Risk4  = ifelse(migrant_dest_q == 1, "Migrant destitution", NA),
         Risk5  = ifelse(worst_lonely_q == 1, "Loneliness", NA),
         Risk6  = ifelse(worst_health_q == 1, "Health deprivation", NA),
         Risk7  = ifelse(hle_birth_q == 1,    "Healthy life expectancy", NA),
         Risk8  = ifelse(digital_q == 1,      "Digital exclusion", NA),
         Risk9  = ifelse(worst_alone_q == 1,  "Living alone", NA),
         Risk10 = ifelse(worst_imd_q == 1,    "IMD", NA),
         Risk11 = ifelse(destitution_q == 1,  "All destitution", NA)) %>% 
  mutate(CombinedRisk = paste(Risk1, Risk2, Risk3, Risk4, Risk5, Risk6, Risk7, Risk8, Risk9, Risk10, Risk11, sep = ", ")) %>% 
  
  mutate(CombinedRisk = gsub("NA, ", "", CombinedRisk)) %>%  # get rid of NAs
  mutate(CombinedRisk = gsub(", NA", "", CombinedRisk)) %>%  # get rid of any trailing NA
  
  select(-starts_with("Risk"))

# look up LAD names
eng_lad_risk = eng_lad_risk %>% 
  left_join(eng_lookup %>% select(LAD17CD, LAD17NM) %>% distinct(), by = "LAD17CD")

# add BRC presence
eng_lad_risk = eng_lad_risk %>% 
  left_join(lad_brc, by = c("LAD17CD" = "lad17cd"))

##
## replace any risks == 99 with zero
##
eng_msoa_risk = eng_msoa_risk %>%
  mutate_at(vars(ends_with("_q")), ~ifelse(. == 99, 0, .))

eng_lad_risk = eng_lad_risk %>% 
  mutate_at(vars(ends_with("_q")), ~ifelse(. == 99, 0, .))

##
## save combined risks
##
write_csv(eng_msoa_risk, file.path(data.dir.out, "England - MSOA - risks.csv"))
write_csv(eng_lad_risk,  file.path(data.dir.out, "England - LAD - risks.csv"))

# make a human-readable version of the dataset for the Excel file
eng_lad_risk_xl = eng_lad_risk %>% 
  # count the number of 1s (highest risk) for each LA (used to sort the data)
  mutate(`No. 1s` = ifelse(!is.na(worst_fires_q) & worst_fires_q == 1, 1, 0) + ifelse(!is.na(worst_floods_q) & worst_floods_q == 1, 1, 0) + 
           ifelse(!is.na(worst_lonely_q) & worst_lonely_q == 1, 1, 0) + ifelse(!is.na(worst_health_q) & worst_health_q == 1, 1, 0) + ifelse(!is.na(hle_birth_q) & hle_birth_q == 1, 1, 0) + 
           ifelse(!is.na(displacement_q) & displacement_q == 1, 1, 0) + ifelse(!is.na(migrant_dest_q) & migrant_dest_q == 1, 1, 0) + 
           ifelse(!is.na(digital_q) & digital_q == 1, 1, 0) + ifelse(!is.na(worst_alone_q) & worst_alone_q == 1, 1, 0) +
           ifelse(!is.na(worst_imd_q) & worst_imd_q == 1, 1, 0) + ifelse(!is.na(destitution_q) & destitution_q == 1, 1, 0)) %>% 
  
  # multiply the risk scores (used to sort the data)
  mutate(`Total score` = worst_fires_q %**% worst_floods_q %**% 
           worst_lonely_q %**% worst_health_q %**% hle_birth_q %**% 
           displacement_q %**% migrant_dest_q %**% 
           digital_q %**% worst_alone_q %**%
           worst_imd_q %**% destitution_q) %>% 
  
  # prettify columns
  select(`Local Authority code` = LAD17CD, `Local Authority` = LAD17NM, 
         `Fire risk` = worst_fires_q, `Flooding risk` = worst_floods_q, 
         `Displacement risk` = displacement_q, `Migrant destitution risk` = migrant_dest_q,
         `Loneliness risk` = worst_lonely_q, `Health deprivation risk` = worst_health_q, `Healthy life expectancy risk` = hle_birth_q,
         `Digital exclusion risk` = digital_q, `Living alone risk` = worst_alone_q,
         `Multiple deprivation risk` = worst_imd_q, `All destitution risk` = destitution_q,
         `BRC services?` = BRC_services, `BRC shops?` = BRC_shops, `BRC properties?` = BRC_props,
         `Combined risk` = CombinedRisk, `Total score`, `No. 1s`) %>% 
  
  # put LAs with most highest risks first
  arrange(desc(`No. 1s`), `Total score`)

# add to Excel file
addWorksheet(risky_lads_wb, "England")
writeData(risky_lads_wb, sheet="England", x=as.data.frame(eng_lad_risk_xl))


#################################################################################################################
## Wales
## - fires in FRAs
## - floods in MSOAs
## - displacement in LADs
## - migrant destitution in LADs
## - loneliness in MSOAs
## - health deprivation in MSOAs
## - healthy life expectancy in LADs
## - digital exclusion in LADs
##

##
## load all Wales data
##
# Middle Layer Super Output Areas (December 2011) Names and Codes in England and Wales
# source: https://geoportal.statistics.gov.uk/datasets/middle-layer-super-output-areas-december-2011-names-and-codes-in-england-and-wales
wal_msoa = read_csv("https://opendata.arcgis.com/datasets/6b82649791b3481692d63d39a653143c_0.csv")

wal_msoa_floods = read_csv(file.path(data.dir.processed, "MSOAs in flood risk zones.csv"))   # from `prep flood risks.r`
wal_msoa_loneliness = read_csv("https://github.com/matthewgthomas/loneliness/raw/master/Wales/msoa_loneliness.csv")
wal_msoa_alone = uk_msoa_alone

wal_lsoa_imd = uk_lsoa_imd %>% select(LSOA, IMD_decile, Health_decile)

wal_lad_hle = read_csv(file.path(data.dir.processed, "Healthy life expectancy - Local Authorities - whole UK.csv"))  # from `prep healthy life expectancy .r`
wal_lad_displacement = read_csv(file.path(data.dir.processed, "UK - LAD - displacement.csv"))         # from `prep displacement.r`
wal_lad_destitution = read_csv(file.path(data.dir.processed, "Destitution - Local Authorities - whole UK.csv")) # from `prep destitution.r`
wal_lad_digital = read_csv(file.path(data.dir.processed, "digital exclusion.csv")) %>%        # from `prep digital exclusion.r`
  rename(lad17cd = la_codes)

wal_fra_fires = read_csv(file.path(data.dir.processed, "Fires - FRA - Wales.csv"))           # from `prep fires.r`

wal_lookup = read_csv("https://opendata.arcgis.com/datasets/fe6c55f0924b4734adf1cf7104a0173e_0.csv") %>% 
  select(starts_with("LSOA"), starts_with("MSOA"), starts_with("LAD")) %>% 
  distinct()

# Local Authority District to Fire and Rescue Authority (December 2017) Lookup in England and Wales
# source: https://geoportal.statistics.gov.uk/datasets/local-authority-district-to-fire-and-rescue-authority-december-2017-lookup-in-england-and-wales-
fra_to_lad = read_csv("https://opendata.arcgis.com/datasets/fcd35bcc7cf64b68abb53a0097105914_0.csv")

##
## keep Wales data only
##
wal_msoa             = wal_msoa %>% filter(startsWith(MSOA11CD, "W"))
wal_msoa_floods      = wal_msoa_floods %>% filter(startsWith(MSOA11CD, "W"))
wal_msoa_alone       = wal_msoa_alone %>% filter(startsWith(msoa11cd, "W"))
wal_msoa_loneliness  = wal_msoa_loneliness %>% filter(startsWith(msoa11cd, "W"))
wal_lsoa_imd         = wal_lsoa_imd %>% filter(startsWith(LSOA, "W"))
wal_lad_displacement = wal_lad_displacement %>% filter(startsWith(LAD19CD, "W"))
wal_lad_destitution  = wal_lad_destitution %>% filter(startsWith(lad17cd, "W"))
wal_lad_digital      = wal_lad_digital %>% filter(startsWith(lad17cd, "W"))
wal_lad_hle          = wal_lad_hle %>% filter(startsWith(lad17cd, "W"))

##
## data tweaking
##
# rename flooding variable
wal_msoa_floods = wal_msoa_floods %>% rename(n_people_flood = n)

# loneliness: keep only loneliness indices >= 0 (and cut out unnecessary columns)
wal_msoa_loneliness = wal_msoa_loneliness %>% 
  # filter(loneills_2018 >= 0) %>% 
  select(msoa11cd, loneills_2018, loneills_2018_class)

##
## calculate fisher splits/categories for each risk
##
# fires
wal_fra_fires = wal_fra_fires %>% add_risk_quantiles("dens_fires", output.col = "fires")

# floods
wal_msoa_floods = wal_msoa_floods %>% add_risk_quantiles("n_people_flood", output.col = "floods")

# displacement
wal_lad_displacement = wal_lad_displacement %>% add_risk_quantiles("Sec95", output.col = "displacement")

# loneliness
wal_msoa_loneliness = wal_msoa_loneliness %>% add_risk_quantiles("loneills_2018", "lonely")

# healthy life expectancy
wal_lad_hle = wal_lad_hle %>% add_risk_quantiles("HLE_birth", "hle_birth")

# digital exclusion
wal_lad_digital = wal_lad_digital %>% add_risk_quantiles("digital_total_mult", "digital")

# living alone
wal_msoa_alone = wal_msoa_alone %>% add_risk_quantiles("prop_alone", "alone")

# health deprivation - link the LSOAs to MSOAs and mark MSOAs as most deprived if any of their LSOAs are most-deprived
wal_msoa_imd = wal_lsoa_imd %>% 
  left_join(wal_lookup %>% select(LSOA11CD, MSOA11CD), by = c("LSOA" = "LSOA11CD")) %>% 
  
  # mark MSOAs with the most-deprived LSOA in its bounds
  group_by(MSOA11CD) %>% 
  summarise(Worst_Health_decile = min(Health_decile),
            Worst_IMD_decile = min(IMD_decile)) %>%  
  
  mutate(health_q = case_when(
    Worst_Health_decile %in% c(1, 2) ~ 1,   # most deprived
    Worst_Health_decile %in% c(3, 4) ~ 2,
    Worst_Health_decile %in% c(5, 6) ~ 3,
    Worst_Health_decile %in% c(7, 8) ~ 4,
    Worst_Health_decile %in% c(9, 10) ~ 5   # least deprived
  ),
  
  imd_q = case_when(
    Worst_IMD_decile %in% c(1, 2) ~ 1,   # most deprived
    Worst_IMD_decile %in% c(3, 4) ~ 2,
    Worst_IMD_decile %in% c(5, 6) ~ 3,
    Worst_IMD_decile %in% c(7, 8) ~ 4,
    Worst_IMD_decile %in% c(9, 10) ~ 5   # least deprived
  ))

# migrant destitution and all destitution - already in deciles, so just convert to quintiles by halving and rounding up
wal_lad_destitution = wal_lad_destitution %>% 
  mutate(destitution_q = ceiling(destitution_all / 2),
         migrant_dest_q = ceiling(destitution_migrant / 2)) %>% 
  
  # reverse-score the quantiles so highest destitution == 1
  mutate(destitution_q = (quants + 1) - destitution_q,
         migrant_dest_q = (quants + 1) - migrant_dest_q)

##
## combined risk at MSOA level: floods and health deprivation
##
# merge all MSOA data into a single dataframe
wal_msoa_risk = wal_msoa %>% 
  left_join(wal_msoa_floods, by = "MSOA11CD") %>% 
  left_join(wal_msoa_imd, by = "MSOA11CD") %>% 
  left_join(wal_msoa_loneliness, by = c("MSOA11CD" = "msoa11cd")) %>%
  left_join(wal_msoa_alone, by = c("MSOA11CD" = "msoa11cd"))

# replace NAs with zeroes for the risk quintiles
wal_msoa_risk = wal_msoa_risk %>% 
  replace_na(list(floods_q = 99, 
                  lonely_q = 99,
                  health_q = 99,
                  imd_q    = 99,
                  alone_q  = 99))

# calculate combined risks
wal_msoa_risk = wal_msoa_risk %>% 
  mutate(Risk1 = ifelse(floods_q == 1, "Flooding", NA),
         Risk2 = ifelse(lonely_q == 1, "Loneliness", NA),
         Risk3 = ifelse(health_q == 1, "Health deprivation", NA),
         Risk4 = ifelse(alone_q == 1,  "Living alone", NA),
         Risk5 = ifelse(imd_q == 1,    "IMD", NA)) %>% 
  mutate(CombinedRisk = paste(Risk1, Risk2, Risk3, Risk4, Risk5, sep = ", ")) %>% 
  
  mutate(CombinedRisk = gsub("NA, ", "", CombinedRisk)) %>%  # get rid of NAs
  mutate(CombinedRisk = gsub(", NA", "", CombinedRisk)) %>%  # get rid of any trailing NA
  
  select(-starts_with("Risk"))

##
## combined risk LAD level: floods, health deprivation, displacement, and digital exclusion
##
# take the MSOA risks and aggregate into LADs - by grouping them with the worst MSOA risk in each category
wal_lad_risk = wal_msoa_risk %>% 
  # look up the LADs for these MSOAs
  left_join(wal_lookup %>% select(MSOA11CD, LAD17CD), by = "MSOA11CD") %>% 
  
  # take the score of the worst-performing MSOA within each LAD
  group_by(LAD17CD) %>% 
  summarise(worst_floods_q = min(floods_q),
            worst_lonely_q = min(lonely_q),
            worst_health_q = min(health_q),
            worst_alone_q  = min(alone_q),
            worst_imd_q    = min(imd_q),
            
            # calculate highest/worst risks in each LAD
            worst_floods = ifelse(all(is.na(n_people_flood)), NA, max(n_people_flood, na.rm = T)),  # only calculate max. if not all MSOAs contain NA
            worst_lonely = max(loneills_2018, na.rm = T),
            worst_health = min(Worst_Health_decile, na.rm = T),
            worst_alone  = (sum(n_one_person_hh, na.rm = T) + sum(n_lone_parents, na.rm = T)) / sum(n_people_total, na.rm = T),  # proportion of people living alone in whole LAD
            worst_imd    = min(Worst_IMD_decile, na.rm = T),
            
            # calculate averages (medians) for each risk in each LAD
            median_floods = median(n_people_flood, na.rm = T),
            median_lonely = median(loneills_2018, na.rm = T),
            median_health = median(Worst_Health_decile, na.rm = T),
            median_alone  = median(prop_alone, na.rm = T),
            median_imd    = median(Worst_IMD_decile, na.rm = T)) %>% 
  
  left_join(lad_codes, by = "LAD17CD") %>%   # get LAD 2019 codes
  
  # merge displacement and digital exclusion
  left_join(wal_lad_displacement, by = "LAD19CD") %>%
  left_join(wal_lad_digital, by = c("LAD17CD" = "lad17cd")) %>% 
  left_join(wal_lad_hle, by = c("LAD17CD" = "lad17cd"))%>% 
  left_join(wal_lad_destitution, by = c("LAD17CD" = "lad17cd"))

# calculate combined risks
wal_lad_risk = wal_lad_risk %>% 
  mutate(Risk1  = ifelse(worst_floods_q == 1, "Flooding", NA),
         Risk2  = ifelse(displacement_q == 1, "Displacement", NA),
         Risk3  = ifelse(migrant_dest_q == 1, "Migrant destitution", NA),
         Risk4  = ifelse(worst_lonely_q == 1, "Loneliness", NA),
         Risk5  = ifelse(worst_health_q == 1, "Health deprivation", NA),
         Risk6  = ifelse(hle_birth_q == 1,    "Healthy life expectancy", NA),
         Risk7  = ifelse(digital_q == 1,      "Digital exclusion", NA),
         Risk8  = ifelse(worst_alone_q == 1,  "Living alone", NA),
         Risk9  = ifelse(worst_imd_q == 1,    "IMD", NA),
         Risk10 = ifelse(destitution_q == 1,  "All destitution", NA)) %>% 
  mutate(CombinedRisk = paste(Risk1, Risk2, Risk3, Risk4, Risk5, Risk6, Risk7, Risk8, Risk9, Risk10, sep = ", ")) %>% 
  
  mutate(CombinedRisk = gsub("NA, ", "", CombinedRisk)) %>%  # get rid of NAs
  mutate(CombinedRisk = gsub(", NA", "", CombinedRisk)) %>%  # get rid of any trailing NA
  
  select(-starts_with("Risk"))

# look up LAD names
wal_lad_risk = wal_lad_risk %>% 
  left_join(wal_lookup %>% select(LAD17CD, LAD17NM) %>% distinct(), by = "LAD17CD")

wal_lad_risk = wal_lad_risk %>% 
  left_join(lad_brc, by = c("LAD17CD" = "lad17cd"))

##
## combined risk at FRA level: everything
##
# take the MSOA risks and aggregate into LADs - by grouping them with the worst MSOA risk in each category
wal_fra_risk = wal_lad_risk %>% 
  # look up the FRAs for these MSOAs
  left_join(fra_to_lad %>% select(LAD17CD, FRA17CD), by = "LAD17CD") %>% 
  
  # take the score of the worst-performing LAD within each FRA
  group_by(FRA17CD) %>% 
  summarise(worst_floods_q = min(worst_floods_q),
            worst_health_q = min(worst_health_q),
            worst_lonely_q = min(worst_lonely_q),
            worst_hle_q = min(hle_birth_q),
            worst_displacement_q = min(displacement_q),
            worst_migrant_dest_q = min(migrant_dest_q),
            worst_digital_q = min(digital_q),
            worst_alone_q = min(worst_alone_q),
            worst_imd_q = min(worst_imd_q),
            worst_destitution_q = min(destitution_q)) %>% 
  
  # merge fires
  left_join(wal_fra_fires, by = c("FRA17CD" = "FRA19CD"))

# calculate combined risks
wal_fra_risk = wal_fra_risk %>% 
  mutate(Risk1  = ifelse(fires_q == 1,              "Fires", NA),
         Risk2  = ifelse(worst_floods_q == 1,       "Flooding", NA),
         Risk3  = ifelse(worst_displacement_q == 1, "Displacement", NA),
         Risk4  = ifelse(worst_migrant_dest_q == 1, "Migrant destitution", NA),
         Risk5  = ifelse(worst_lonely_q == 1,       "Loneliness", NA),
         Risk6  = ifelse(worst_health_q == 1,       "Health deprivation", NA),
         Risk7  = ifelse(worst_hle_q == 1,          "Healthy life expectancy", NA),
         Risk8  = ifelse(worst_digital_q == 1,      "Digital exclusion", NA),
         Risk9  = ifelse(worst_alone_q == 1,        "Living alone", NA),
         Risk10 = ifelse(worst_imd_q == 1,          "IMD", NA),
         Risk11 = ifelse(worst_destitution_q == 1,  "All destitution", NA)) %>% 
  mutate(CombinedRisk = paste(Risk1, Risk2, Risk3, Risk4, Risk5, Risk6, Risk7, Risk8, Risk9, Risk10, Risk11, sep = ", ")) %>% 
  
  mutate(CombinedRisk = gsub("NA, ", "", CombinedRisk)) %>%  # get rid of NAs
  mutate(CombinedRisk = gsub(", NA", "", CombinedRisk)) %>%  # get rid of any trailing NA
  
  select(-starts_with("Risk"))

# look up LAD names
wal_fra_risk = wal_fra_risk %>% 
  left_join(fra_to_lad %>% select(FRA17CD, FRA17NM) %>% distinct(), by = "FRA17CD")

##
## replace any risks == 99 with zero
##
wal_msoa_risk = wal_msoa_risk %>%
  mutate_at(vars(ends_with("_q")), ~ifelse(. == 99, 0, .))

wal_lad_risk = wal_lad_risk %>% 
  mutate_at(vars(ends_with("_q")), ~ifelse(. == 99, 0, .))

wal_fra_risk = wal_fra_risk %>% 
  mutate_at(vars(ends_with("_q")), ~ifelse(. == 99, 0, .))

##
## save combined risks
##
write_csv(wal_msoa_risk, file.path(data.dir.out, "Wales - MSOA - risks.csv"))
write_csv(wal_lad_risk,  file.path(data.dir.out, "Wales - LAD - risks.csv"))
write_csv(wal_fra_risk,  file.path(data.dir.out, "Wales - FRA - risks.csv"))

# make a human-readable version of the dataset for the Excel file
wal_lad_risk_xl = wal_lad_risk %>% 
  # count the number of 1s (highest risk) for each LA
  mutate(`No. 1s` = ifelse(!is.na(worst_floods_q) & worst_floods_q == 1, 1, 0) + 
           ifelse(!is.na(worst_health_q) & worst_health_q == 1, 1, 0) + ifelse(!is.na(worst_lonely_q) & worst_lonely_q == 1, 1, 0) + ifelse(!is.na(hle_birth_q) & hle_birth_q == 1, 1, 0) + 
           ifelse(!is.na(displacement_q) & displacement_q == 1, 1, 0) + ifelse(!is.na(migrant_dest_q) & migrant_dest_q == 1, 1, 0) + 
           ifelse(!is.na(digital_q) & digital_q == 1, 1, 0) + ifelse(!is.na(worst_alone_q) & worst_alone_q == 1, 1, 0) +
           ifelse(!is.na(worst_imd_q) & worst_imd_q == 1, 1, 0) + ifelse(!is.na(destitution_q) & destitution_q == 1, 1, 0)) %>% 
  
  # multiply the risk scores (used to sort the data)
  mutate(`Total score` = worst_floods_q %**% 
           worst_health_q %**% worst_lonely_q %**% hle_birth_q %**% 
           displacement_q %**% migrant_dest_q %**% 
           digital_q %**% worst_alone_q %**%
           worst_imd_q %**% destitution_q) %>% 
  
  # prettify columns
  select(`Local Authority code` = LAD17CD, `Local Authority` = LAD17NM, 
         `Flooding risk` = worst_floods_q, 
         `Displacement risk` = displacement_q, `Migrant destitution risk` = migrant_dest_q,
         `Loneliness risk` = worst_lonely_q, 
         `Health deprivation risk` = worst_health_q, `Healthy life expectancy risk` = hle_birth_q,
         `Digital exclusion risk` = digital_q,  `Living alone risk` = worst_alone_q,
         `Multiple deprivation risk` = worst_imd_q, `All destitution risk` = destitution_q,
         `BRC services?` = BRC_services, `BRC shops?` = BRC_shops, `BRC properties?` = BRC_props,
         `Combined risk` = CombinedRisk, `Total score`, `No. 1s`) %>% 
  
  # put LAs with most highest risks first
  arrange(desc(`No. 1s`), `Total score`)

# add to Excel file
addWorksheet(risky_lads_wb, "Wales")
writeData(risky_lads_wb, sheet="Wales", x=as.data.frame(wal_lad_risk_xl))


#################################################################################################################
## Scotland
## - fires in MSOAs
## - displacement in LADs
## - migrant destitution in LADs
## - loneliness in MSOAs
## - health deprivation in LSOAs
## - healthy life expectancy in LADs
## - digital exclusion in LADs
##

##
## load all Scotland data
##
# Intermediate Zones (December 2011) Names and Codes in Scotland
# source: https://geoportal.statistics.gov.uk/datasets/intermediate-zones-december-2011-names-and-codes-in-scotland
sco_msoa = read_csv("https://opendata.arcgis.com/datasets/02f78aaf05df4f48a84cc5b10751ba3c_0.csv")

sco_msoa_fires = read_csv(file.path(data.dir.processed, "Fires - MSOA - Scotland.csv"))       # from `prep fires.r`
sco_msoa_loneliness = read_csv("https://github.com/matthewgthomas/loneliness/raw/master/Scotland/msoa_loneliness.csv")  # from https://github.com/matthewgthomas/loneliness
sco_msoa_alone = uk_msoa_alone

sco_lsoa_imd = uk_lsoa_imd %>% select(LSOA, IMD_decile, Health_decile)

sco_lad_displacement = read_csv(file.path(data.dir.processed, "UK - LAD - displacement.csv"))         # from `prep displacement.r`
sco_lad_destitution = read_csv(file.path(data.dir.processed, "Destitution - Local Authorities - whole UK.csv")) # from `prep destitution.r`
sco_lad_hle = read_csv(file.path(data.dir.processed, "Healthy life expectancy - Local Authorities - whole UK.csv"))  # from `prep healthy life expectancy .r`
sco_lad_digital = read_csv(file.path(data.dir.processed, "digital exclusion.csv")) %>%        # from `prep digital exclusion.r`
  rename(lad17cd = la_codes)

# Look-up: Data zone to intermediate zone, local authority, health board, multi-member ward, Scottish parliamentary constituency 
# source: https://www2.gov.scot/Topics/Statistics/SIMD/Look-Up
GET("https://www2.gov.scot/Resource/0053/00534447.xlsx", write_disk(tf <- tempfile(fileext = ".xlsx")))

sco_lookup = read_excel(tf, sheet = "SIMD16 DZ look-up data") %>% 
  select(LSOA11CD = DZ, LSOA11NM = DZname, MSOA11CD = IZcode, MSOA11NM = IZname, LAD17CD = LAcode, LAD17NM = LAname) %>% 
  distinct()


##
## keep Scotland data only
##
sco_msoa_fires       = sco_msoa_fires %>% filter(startsWith(IZcode, "S"))
sco_msoa_loneliness  = sco_msoa_loneliness %>% filter(startsWith(InterZone, "S"))
sco_msoa_alone       = sco_msoa_alone %>% filter(startsWith(msoa11cd, "S"))
sco_lsoa_imd         = sco_lsoa_imd %>% filter(startsWith(LSOA, "S"))
sco_lad_displacement = sco_lad_displacement %>% filter(startsWith(LAD19CD, "S"))
sco_lad_digital      = sco_lad_digital %>% filter(startsWith(lad17cd, "S"))
sco_lad_hle          = sco_lad_hle %>% filter(startsWith(lad17cd, "S"))
sco_lad_destitution  = sco_lad_destitution %>% filter(startsWith(lad17cd, "S"))

##
## data tweaking
##
sco_msoa = sco_msoa %>% 
  select(MSOA11CD = IZ11CD, MSOA11NM = IZ11NM)

# loneliness: keep only loneliness indices >= 0 (and cut out unnecessary columns)
sco_msoa_loneliness = sco_msoa_loneliness %>% 
  # filter(loneills_2018 >= 0) %>% 
  select(InterZone, loneills_2018, loneills_2018_class)

##
## calculate fisher splits/categories for each risk
##
# fires
sco_msoa_fires = sco_msoa_fires %>% add_risk_quantiles("dens_fires", output.col = "fires")

# displacement
sco_lad_displacement = sco_lad_displacement %>% add_risk_quantiles("Sec95", output.col = "displacement")

# loneliness
sco_msoa_loneliness = sco_msoa_loneliness %>% add_risk_quantiles("loneills_2018", "lonely")

# healthy life expectancy
sco_lad_hle = sco_lad_hle %>% add_risk_quantiles("HLE_birth", "hle_birth")

# digital exclusion
sco_lad_digital = sco_lad_digital %>% add_risk_quantiles("digital_total_mult", "digital")

# living alone
sco_msoa_alone = sco_msoa_alone %>% add_risk_quantiles("prop_alone", "alone")

# health deprivation - link the LSOAs to MSOAs and mark MSOAs as most deprived if any of their LSOAs are most-deprived
sco_msoa_imd = sco_lsoa_imd %>% 
  left_join(sco_lookup %>% select(LSOA11CD, MSOA11CD), by = c("LSOA" = "LSOA11CD")) %>% 
  
  group_by(MSOA11CD) %>% 
  summarise(Worst_Health_decile = min(Health_decile),
            Worst_IMD_decile = min(IMD_decile)) %>%  # mark MSOA with the most-deprived LSOA in its bounds
  
  mutate(health_q = case_when(
    Worst_Health_decile %in% c(1, 2) ~ 1,   # most deprived
    Worst_Health_decile %in% c(3, 4) ~ 2,
    Worst_Health_decile %in% c(5, 6) ~ 3,
    Worst_Health_decile %in% c(7, 8) ~ 4,
    Worst_Health_decile %in% c(9, 10) ~ 5   # least deprived
  ),
  
  imd_q = case_when(
    Worst_IMD_decile %in% c(1, 2) ~ 1,   # most deprived
    Worst_IMD_decile %in% c(3, 4) ~ 2,
    Worst_IMD_decile %in% c(5, 6) ~ 3,
    Worst_IMD_decile %in% c(7, 8) ~ 4,
    Worst_IMD_decile %in% c(9, 10) ~ 5   # least deprived
  ))

# migrant destitution and all destitution - already in deciles, so just convert to quintiles by halving and rounding up
sco_lad_destitution = sco_lad_destitution %>% 
  mutate(destitution_q = ceiling(destitution_all / 2),
         migrant_dest_q = ceiling(destitution_migrant / 2)) %>% 
  
  # reverse-score the quantiles so highest destitution == 1
  mutate(destitution_q = (quants + 1) - destitution_q,
         migrant_dest_q = (quants + 1) - migrant_dest_q)

##
## combined risk at MSOA level: fires and health deprivation
##
# merge all LSOA data into a single dataframe
sco_msoa_risk = sco_msoa %>% 
  left_join(sco_msoa_fires, by = c("MSOA11CD" = "IZcode")) %>% 
  left_join(sco_msoa_imd, by = "MSOA11CD") %>% 
  left_join(sco_msoa_loneliness, by = c("MSOA11CD" = "InterZone")) %>% 
  left_join(sco_msoa_alone, by = c("MSOA11CD" = "msoa11cd"))

# replace NAs with zeroes for the risk quintiles
sco_msoa_risk = sco_msoa_risk %>% 
  replace_na(list(fires_q  = 99,
                  lonely_q = 99,
                  health_q = 99,
                  imd_q    = 99,
                  alone_q  = 99))

# calculate combined risks
sco_msoa_risk = sco_msoa_risk %>% 
  mutate(Risk1 = ifelse(fires_q == 1,  "Fires", NA),
         Risk2 = ifelse(lonely_q == 1, "Loneliness", NA),
         Risk3 = ifelse(health_q == 1, "Health deprivation", NA),
         Risk4 = ifelse(alone_q == 1,  "Living alone", NA),
         Risk5 = ifelse(imd_q == 1,    "IMD", NA)) %>% 
  mutate(CombinedRisk = paste(Risk1, Risk2, Risk3, Risk4, Risk5, sep = ", ")) %>% 
  
  mutate(CombinedRisk = gsub("NA, ", "", CombinedRisk)) %>%  # get rid of NAs
  mutate(CombinedRisk = gsub(", NA", "", CombinedRisk)) %>%  # get rid of any trailing NA
  
  select(-starts_with("Risk"))

##
## combined risk at LAD level: for everthing
##
# take the MSOA risks and aggregate into LADs - by grouping them with the worst MSOA risk in each category
sco_lad_risk = sco_msoa_risk %>% 
  # lookup the LADs for these MSOAs
  left_join(sco_lookup %>% select(MSOA11CD, LAD17CD), by = "MSOA11CD") %>% 
  
  # take the score of the worst-performing MSOA within each LAD
  group_by(LAD17CD) %>% 
  summarise(worst_fires_q  = min(fires_q),
            worst_lonely_q = min(lonely_q),
            worst_health_q = min(health_q),
            worst_alone_q  = min(alone_q),
            worst_imd_q    = min(imd_q),
            
            # calculate highest/worst risks in each LAD
            worst_fires  = ifelse(all(is.na(dens_fires)), NA, max(dens_fires, na.rm = T)),  # only calculate max. if not all MSOAs contain NA
            worst_lonely = max(loneills_2018, na.rm = T),
            worst_health = min(Worst_Health_decile, na.rm = T),
            worst_alone  = (sum(n_one_person_hh, na.rm = T) + sum(n_lone_parents, na.rm = T)) / sum(n_people_total, na.rm = T),  # proportion of people living alone in whole LAD
            worst_imd    = min(Worst_IMD_decile, na.rm = T),
            
            # calculate averages (medians) for each risk in each LAD
            median_fires  = median(dens_fires, na.rm = T),
            median_lonely = median(loneills_2018, na.rm = T),
            median_health = median(Worst_Health_decile, na.rm = T),
            median_alone  = median(prop_alone, na.rm = T),
            median_imd    = median(Worst_IMD_decile, na.rm = T)) %>% 
  
  left_join(lad_codes, by = "LAD17CD") %>%   # get LAD 2019 codes
  
  # merge displacement and digital exclusion
  left_join(sco_lad_displacement, by = "LAD19CD") %>% 
  left_join(sco_lad_digital, by = c("LAD17CD" = "lad17cd")) %>% 
  left_join(sco_lad_hle, by = c("LAD17CD" = "lad17cd")) %>% 
  left_join(sco_lad_destitution, by = c("LAD17CD" = "lad17cd"))

# calculate combined risks
sco_lad_risk = sco_lad_risk %>% 
  mutate(Risk1  = ifelse(worst_fires_q == 1,  "Fires", NA),
         Risk2  = ifelse(displacement_q == 1, "Displacement", NA),
         Risk3  = ifelse(migrant_dest_q == 1, "Migrant destitution", NA),
         Risk4  = ifelse(worst_lonely_q == 1, "Loneliness", NA),
         Risk5  = ifelse(worst_health_q == 1, "Health deprivation", NA),
         Risk6  = ifelse(hle_birth_q == 1,    "Healthy life expectancy", NA),
         Risk7  = ifelse(digital_q == 1,      "Digital exclusion", NA),
         Risk8  = ifelse(worst_alone_q == 1,  "Living alone", NA),
         Risk9  = ifelse(worst_imd_q == 1,    "IMD", NA),
         Risk10 = ifelse(destitution_q == 1,  "All destitution", NA)) %>% 
  mutate(CombinedRisk = paste(Risk1, Risk2, Risk3, Risk4, Risk5, Risk6, Risk7, Risk8, Risk9, Risk10, sep = ", ")) %>% 
  
  mutate(CombinedRisk = gsub("NA, ", "", CombinedRisk)) %>%  # get rid of NAs
  mutate(CombinedRisk = gsub(", NA", "", CombinedRisk)) %>%  # get rid of any trailing NA
  
  select(-starts_with("Risk"))

# look up LAD names
sco_lad_risk = sco_lad_risk %>% 
  left_join(sco_lookup %>% select(LAD17CD, LAD17NM) %>% distinct(), by = "LAD17CD")

sco_lad_risk = sco_lad_risk %>% 
  left_join(lad_brc, by = c("LAD17CD" = "lad17cd"))

##
## replace any risks == 99 with zero
##
sco_msoa_risk = sco_msoa_risk %>%
  mutate_at(vars(ends_with("_q")), ~ifelse(. == 99, 0, .))

sco_lad_risk = sco_lad_risk %>% 
  mutate_at(vars(ends_with("_q")), ~ifelse(. == 99, 0, .))

##
## save combined risks
##
write_csv(sco_msoa_risk, file.path(data.dir.out, "Scotland - MSOA - risks.csv"))
write_csv(sco_lad_risk,  file.path(data.dir.out,  "Scotland - LAD - risks.csv"))

# make a human-readable version of the dataset for the Excel file
sco_lad_risk_xl = sco_lad_risk %>% 
  # count the number of 1s (highest risk) for each LA
  mutate(`No. 1s` = ifelse(!is.na(worst_fires_q) & worst_fires_q == 1, 1, 0) + 
           ifelse(!is.na(worst_health_q) & worst_health_q == 1, 1, 0) + ifelse(!is.na(worst_lonely_q) & worst_lonely_q == 1, 1, 0) + ifelse(!is.na(hle_birth_q) & hle_birth_q == 1, 1, 0) + 
           ifelse(!is.na(displacement_q) & displacement_q == 1, 1, 0) + ifelse(!is.na(migrant_dest_q) & migrant_dest_q == 1, 1, 0) + 
           ifelse(!is.na(digital_q) & digital_q == 1, 1, 0) + ifelse(!is.na(worst_alone_q) & worst_alone_q == 1, 1, 0) +
           ifelse(!is.na(worst_imd_q) & worst_imd_q == 1, 1, 0) + ifelse(!is.na(destitution_q) & destitution_q == 1, 1, 0)) %>% 
  
  # multiply the risk scores (used to sort the data)
  mutate(`Total score` = worst_fires_q %**% 
           worst_health_q %**% worst_lonely_q %**% hle_birth_q %**% 
           displacement_q %**% migrant_dest_q %**% 
           digital_q %**% worst_alone_q %**%
           worst_imd_q %**% destitution_q) %>% 
  
  # prettify columns
  select(`Local Authority code` = LAD17CD, `Local Authority` = LAD17NM, 
         `Fire risk` = worst_fires_q, 
         `Displacement risk` = displacement_q, `Migrant destitution risk` = migrant_dest_q,
         `Loneliness risk` = worst_lonely_q, 
         `Health deprivation risk` = worst_health_q, `Healthy life expectancy risk` = hle_birth_q,
         `Digital exclusion risk` = digital_q, `Living alone risk` = worst_alone_q,
         `Multiple deprivation risk` = worst_imd_q, `All destitution risk` = destitution_q,
         `BRC services?` = BRC_services, `BRC shops?` = BRC_shops, `BRC properties?` = BRC_props,
         `Combined risk` = CombinedRisk, `Total score`, `No. 1s`) %>% 
  
  # put LAs with most highest risks first
  arrange(desc(`No. 1s`), `Total score`)

# add to Excel file
addWorksheet(risky_lads_wb, "Scotland")
writeData(risky_lads_wb, sheet="Scotland", x=as.data.frame(sco_lad_risk_xl))


#################################################################################################################
## Northern Ireland
## - floods in LSOAs
## - displacement in LADs
## - loneliness in LSOAs
## - health deprivation in LSOAs
## - healthy life expectancy in LADs
## - digital exclusion in LADs
##

##
## load all NI data
##

# Small Areas (2011) to SOAs to Local Government Districts (December 2018) Lookup with Area Classifications in Northern Ireland
# source: https://geoportal.statistics.gov.uk/datasets/small-areas-2011-to-soas-to-local-government-districts-december-2018-lookup-with-area-classifications-in-northern-ireland
ni_lookup = read_csv("https://opendata.arcgis.com/datasets/096a7ccbc8e244cc972189b2f07a321a_0.csv")

# get LSOAs from ^
ni_lsoa = ni_lookup %>% 
  select(LSOA11CD) %>% 
  distinct()

ni_lsoa_floods = read_csv(file.path(data.dir.processed, "LSOAs in flood risk zones.csv"))   # from `prep floods.r`
ni_lsoa_loneliness = read_csv("https://github.com/matthewgthomas/loneliness/raw/master/NI/msoa_loneliness.csv")  # from https://github.com/matthewgthomas/loneliness
ni_lsoa_imd = uk_lsoa_imd %>% select(LSOA, IMD_decile, Health_decile)
ni_lsoa_alone = uk_msoa_alone

ni_lad_hle = read_csv(file.path(data.dir.processed, "Healthy life expectancy - Local Authorities - whole UK.csv"))  # from `prep healthy life expectancy .r`
ni_lad_displacement = read_csv(file.path(data.dir.processed, "UK - LAD - displacement.csv"))         # from `prep displacement.r`
ni_lad_digital = read_csv(file.path(data.dir.processed, "digital exclusion.csv")) %>%        # from `prep digital exclusion.r`
  rename(lad17cd = la_codes)

##
## keep Northern Ireland data only
##
ni_lsoa_floods      = ni_lsoa_floods %>% filter(startsWith(LSOA11CD, "9"))
ni_lsoa_imd         = ni_lsoa_imd %>% filter(startsWith(LSOA, "9"))
ni_lsoa_loneliness  = ni_lsoa_loneliness %>% filter(startsWith(SOA_CODE, "9"))
ni_lsoa_alone       = ni_lsoa_alone %>% filter(startsWith(msoa11cd, "9"))
ni_lad_displacement = ni_lad_displacement %>% filter(startsWith(LAD19CD, "N"))
ni_lad_digital      = ni_lad_digital %>% filter(startsWith(lad17cd, "N"))
ni_lad_hle          = ni_lad_hle %>% filter(startsWith(lad17cd, "N"))

##
## data tweaking
##
# rename flooding variable
ni_lsoa_floods = ni_lsoa_floods %>% rename(n_people_flood = n)

# loneliness: keep only loneliness indices >= 0 (and cut out unnecessary columns)
ni_lsoa_loneliness = ni_lsoa_loneliness %>% 
  # filter(loneills_2018 >= 0) %>% 
  select(SOA_CODE, loneills_2018, loneills_2018_class)

##
## calculate fisher splits/categories for each risk
##
# floods
ni_lsoa_floods = ni_lsoa_floods %>% add_risk_quantiles("n_people_flood", output.col = "floods")

# displacement - all asylum seekers are in Belfast, so no point doing classification
ni_lad_displacement$displacement_q = ifelse(ni_lad_displacement$Sec95 > 0, 1, 5)

# loneliness
ni_lsoa_loneliness = ni_lsoa_loneliness %>% add_risk_quantiles("loneills_2018", "lonely")

# healthy life expectancy
ni_lad_hle = ni_lad_hle %>% add_risk_quantiles("HLE_birth", "hle_birth")

# digital exclusion
ni_lad_digital = ni_lad_digital %>% add_risk_quantiles("digital_total_mult", "digital")

# living alone
ni_lsoa_alone = ni_lsoa_alone %>% add_risk_quantiles("prop_alone", "alone")

# health deprivation - link the LSOAs to lsoas and mark lsoas as most deprived if any of their LSOAs are most-deprived
ni_lsoa_imd = ni_lsoa_imd %>% 
  mutate(health_q = case_when(
    Health_decile %in% c(1, 2) ~ 1,   # most deprived
    Health_decile %in% c(3, 4) ~ 2,
    Health_decile %in% c(5, 6) ~ 3,
    Health_decile %in% c(7, 8) ~ 4,
    Health_decile %in% c(9, 10) ~ 5   # least deprived
  ),
  
  imd_q = case_when(
    IMD_decile %in% c(1, 2) ~ 1,   # most deprived
    IMD_decile %in% c(3, 4) ~ 2,
    IMD_decile %in% c(5, 6) ~ 3,
    IMD_decile %in% c(7, 8) ~ 4,
    IMD_decile %in% c(9, 10) ~ 5   # least deprived
  ))

##
## combined risk at LSOA level: floods and health deprivation
##
# merge all LSOA data into a single dataframe
ni_lsoa_risk = ni_lsoa %>% 
  left_join(ni_lsoa_floods, by = "LSOA11CD") %>% 
  left_join(ni_lsoa_loneliness, by = c("LSOA11CD" = "SOA_CODE")) %>% 
  left_join(ni_lsoa_imd, by = c("LSOA11CD" = "LSOA")) %>% 
  left_join(ni_lsoa_alone, by = c("LSOA11CD" = "msoa11cd"))

# replace NAs with zeroes for the risk quintiles
ni_lsoa_risk = ni_lsoa_risk %>% 
  replace_na(list(floods_q = 0,
                  lonely_q = 0,
                  health_q = 0,
                  imd_q    = 0,
                  alone_q  = 0))

# calculate combined risks
ni_lsoa_risk = ni_lsoa_risk %>% 
  mutate(Risk1 = ifelse(floods_q == 1, "Flooding", NA),
         Risk2 = ifelse(lonely_q == 1, "Loneliness", NA),
         Risk3 = ifelse(health_q == 1, "Health deprivation", NA),
         Risk4 = ifelse(alone_q == 1,  "Living alone", NA),
         Risk5 = ifelse(imd_q == 1,    "IMD", NA)) %>% 
  mutate(CombinedRisk = paste(Risk1, Risk2, Risk3, Risk4, Risk5, sep = ", ")) %>% 
  
  mutate(CombinedRisk = gsub("NA, ", "", CombinedRisk)) %>%  # get rid of NAs
  mutate(CombinedRisk = gsub(", NA", "", CombinedRisk)) %>%  # get rid of any trailing NA
  
  select(-starts_with("Risk"))

##
## combined risk at LAD level: for everthing
##
# take the lsoa risks and aggregate into LADs - by grouping them with the worst lsoa risk in each category
ni_lad_risk = ni_lsoa_risk %>% 
  # lookup the LADs for these lsoas
  left_join(ni_lookup %>% select(LSOA11CD, LAD18CD), by = "LSOA11CD") %>% 
  
  # take the score of the worst-performing lsoa within each LAD
  group_by(LAD18CD) %>% 
  summarise(worst_floods_q = min(floods_q),
            worst_lonely_q = min(lonely_q),
            worst_health_q = min(health_q),
            worst_alone_q  = min(alone_q),
            worst_imd_q    = min(imd_q),
            
            # calculate highest/worst risks in each LAD
            worst_floods = ifelse(all(is.na(n_people_flood)), NA, max(n_people_flood, na.rm = T)),  # only calculate max. if not all MSOAs contain NA
            worst_lonely = max(loneills_2018, na.rm = T),
            worst_health = min(Health_decile, na.rm = T),
            worst_alone  = (sum(n_one_person_hh, na.rm = T) + sum(n_lone_parents, na.rm = T)) / sum(n_people_total, na.rm = T),  # proportion of people living alone in whole LAD
            worst_imd    = min(IMD_decile, na.rm = T),
            
            # calculate averages (medians) for each risk in each LAD
            median_floods = median(n_people_flood, na.rm = T),
            median_lonely = median(loneills_2018, na.rm = T),
            median_health = median(Health_decile, na.rm = T),
            median_alone  = median(prop_alone, na.rm = T),
            median_imd    = median(IMD_decile, na.rm = T)) %>% 
  
  left_join(lad_codes, by = c("LAD18CD" = "LAD17CD")) %>%   # get LAD 2019 codes
  
  # merge displacement and digital exclusion
  left_join(ni_lad_displacement, by = c("LAD18CD" = "LAD19CD")) %>% 
  left_join(ni_lad_digital, by = c("LAD18CD" = "lad17cd")) %>% 
  left_join(ni_lad_hle, by = c("LAD18CD" = "lad17cd"))

# calculate combined risks
ni_lad_risk = ni_lad_risk %>% 
  mutate(Risk1 = ifelse(worst_floods_q == 1, "Flooding", NA),
         Risk2 = ifelse(displacement_q == 1, "Displacement", NA),
         Risk3 = ifelse(worst_health_q == 1, "Health deprivation", NA),
         Risk4 = ifelse(worst_lonely_q == 1, "Loneliness", NA),
         Risk5 = ifelse(hle_birth_q == 1,    "Healthy life expectancy", NA),
         Risk6 = ifelse(digital_q == 1,      "Digital exclusion", NA),
         Risk7 = ifelse(worst_alone_q == 1,  "Living alone", NA),
         Risk8 = ifelse(worst_imd_q == 1,    "IMD", NA)) %>% 
  mutate(CombinedRisk = paste(Risk1, Risk2, Risk3, Risk4, Risk5, Risk6, Risk7, Risk8, sep = ", ")) %>% 
  
  mutate(CombinedRisk = gsub("NA, ", "", CombinedRisk)) %>%  # get rid of NAs
  mutate(CombinedRisk = gsub(", NA", "", CombinedRisk)) %>%  # get rid of any trailing NA
  
  select(-starts_with("Risk"))

# look up LAD names
ni_lad_risk = ni_lad_risk %>% 
  left_join(ni_lookup %>% select(LAD18CD, LAD18NM) %>% distinct(), by = "LAD18CD")

ni_lad_risk = ni_lad_risk %>% 
  left_join(lad_brc, by = c("LAD18CD" = "lad17cd"))

##
## replace any risks == 99 with zero
##
ni_lsoa_risk = ni_lsoa_risk %>%
  mutate_at(vars(ends_with("_q")), ~ifelse(. == 99, 0, .))

ni_lad_risk = ni_lad_risk %>% 
  mutate_at(vars(ends_with("_q")), ~ifelse(. == 99, 0, .))

##
## save combined risks
##
write_csv(ni_lsoa_risk, file.path(data.dir.out, "NI - LSOA - risks.csv"))
write_csv(ni_lad_risk,  file.path(data.dir.out, "NI - LAD - risks.csv"))

# make a human-readable version of the dataset for the Excel file
ni_lad_risk_xl = ni_lad_risk %>% 
  # count the number of 1s (highest risk) for each LA
  mutate(`No. 1s` = ifelse(!is.na(worst_floods_q) & worst_floods_q == 1, 1, 0) + 
           ifelse(!is.na(worst_health_q) & worst_health_q == 1, 1, 0) + ifelse(!is.na(worst_lonely_q) & worst_lonely_q == 1, 1, 0) + ifelse(!is.na(hle_birth_q) & hle_birth_q == 1, 1, 0) + 
           ifelse(!is.na(displacement_q) & displacement_q == 1, 1, 0) + 
           ifelse(!is.na(digital_q) & digital_q == 1, 1, 0) + ifelse(!is.na(worst_alone_q) & worst_alone_q == 1, 1, 0) +
           ifelse(!is.na(worst_imd_q) & worst_imd_q == 1, 1, 0)) %>% 
  
  # multiply the risk scores (used to sort the data)
  mutate(`Total score` = worst_floods_q %**% 
           worst_health_q %**% worst_lonely_q %**% hle_birth_q %**% 
           displacement_q %**% 
           digital_q %**% worst_alone_q %**%
           worst_imd_q) %>% 
  
  # prettify columns
  select(`Local Authority code` = LAD18CD, `Local Authority` = LAD18NM, 
         `Flooding risk` = worst_floods_q, 
         `Displacement risk` = displacement_q, 
         `Loneliness risk` = worst_lonely_q, 
         `Health deprivation risk` = worst_health_q, `Healthy life expectancy risk` = hle_birth_q,
         `Digital exclusion risk` = digital_q, `Living alone risk` = worst_alone_q,
         `Multiple deprivation risk` = worst_imd_q,
         `BRC services?` = BRC_services, `BRC shops?` = BRC_shops, `BRC properties?` = BRC_props,
         `Combined risk` = CombinedRisk, `Total score`, `No. 1s`) %>% 
  
  # put LAs with most highest risks first
  arrange(desc(`No. 1s`), `Total score`)

# add to Excel file
addWorksheet(risky_lads_wb, "Northern Ireland")
writeData(risky_lads_wb, sheet="Northern Ireland", x=as.data.frame(ni_lad_risk_xl))

# write out Excel file
saveWorkbook(risky_lads_wb, risky_lads_file, overwrite = T)
